### ISSUE TITLE
As a developer, I want the site to be styled in UNL template/branding.

### ISSUE THREAD

**Issue by MatthewMeacham** [UNL-CSE-AMBASSADORS/VITA#126]
See email exchange between Meach/Mike Jackson about this. But the site needs to be branded/templated with the UNL styling. This is an absolute must before it goes live January 15th. Focus on all public-facing parts of the site (administrative stuff can be changed over later if this is taking a while).

See this for what it should look like: https://lincolneitc.unl.edu/welcome

You should probably be able to just bring in the resources from https://wdn.unl.edu/ and change class names / add stuff / do whatever it is you need. For right now, just copy these resources into our project. A more sustainable solution will be thought through once this tax season is over.

**Comment by CollinsSpencer** [comment]
https://www.unl.edu/wdn/templates_4.1/css/all.css
