### ISSUE TITLE
Appointment Signup

### ISSUE THREAD

**Issue by 2mnyzs** [UNL-CSE-AMBASSADORS/VITA#2]
- Users need to be able to signup
- Name, email, phone, address?
- Litmus test of questions to determine return complexity
    - Do you sell drugs?
    - Are you military?
    - Do you gamble?
    - Etc
    - User Litmus questions to also determine preparer cert requirements
- Language requirements
    - English, Spanish, C++, etc
- Choose site, then day, then time
- Gets an email confirming appointment
- Adds it into database
- Should be stored on the >queue

**Comment by MatthewMeacham** [comment]
Closing this since this is basically the PR we just closed.
