### ISSUE TITLE
As a site admin, I need a place to give/revoke permissions to a volunteer so that we can moderate who has access to what.

### ISSUE THREAD

**Issue by MatthewMeacham** [UNL-CSE-AMBASSADORS/VITA#80]
Site admins need a place to see every volunteer, and every permission, and be able to give/revoke permissions to volunteers. See https://docs.google.com/document/d/1w2R6Z8CusZ99VVZnT_4zRbyz2KMW_hK9YETObYOvuRw/edit for more information on what we're thinking about on this /management/permissions/ page

**Comment by 2mnyzs** [comment]
This functionality has been added per pull 104: https://github.com/UNL-CSE-AMBASSADORS/VITA/pull/104
